server:
  port: 8082

spring:
  profiles:
    active: PROD
  datasource:
    url: jdbc:postgresql://dpg-cuuvq4dds78s7387qa6g-a.oregon-postgres.render.com:5432/aws_postgres_bd_pu6c
    username: aws_postgres_bd_pu6c_user
    password: ZSkHJr002ddgo7FvHoohjPHYgjx5AocZ
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: info